#install.packages("pdftools")
#install.packages("writexl")
#install.packages("tabulizer")
#install.packages("rJava")
#install.packages("tesseract")
#install.packages("translateR")
library(pdftools)
library(stringr)
library(tabulizer)
library(tesseract)
library(rJava)
library(xlsx)
library(translateR)
getGoogleLanguages()
#C:\Users\saurav.an.kumar\Documents\Cliffton Strengths
setwd("C:/Users/saurav.an.kumar/Documents/Cliffton Strengths/")
#pdf_1 <- pdf_text("1000_AAJFA3549B_Q1_2019-20.pdf",upw = "AAJFA354$$1234")
pdf_1 <- pdf_text("Full_Strength_Report.pdf",get_n_pages(1))
pdf_2 <- unlist(str_split(pdf_1, "[\\r\\n]+"))
pdf_3 <- str_split_fixed(str_trim(pdf_2), "\\s{2,}", 6)
write.xlsx(pdf_3, "test.xlsx")
#Full_Strength_Report
pdf_1 <- pdf_text("10134105962002015.pdf")
pdf_2 <- unlist(str_split(pdf_1, "[\\r\\n]+"))
pdf_3 <- str_split_fixed(str_trim(pdf_2), "\\s{2,}", 6)
write.xlsx(pdf_3, "test2.xlsx")

#df <- data.frame(pdf2)
#head(df)
translate(dataset = df,content.field = 'pdf2',google.api.key = )
#------------------------------------OCR Functionality-------------------------------------
tesseract::tesseract_info()
tesseract::tesseract_download(lang = "por", datapath = NULL, progress = interactive())
#pdf <- pdf_ocr_data(pdf = "input_1.pdf", pages = NULL, language = "eng")
#txt <- ocr("cbse sample paper class 7 hindi fa2 .pdf",engine = "hin")
pdf_txt <- ocr("Full_Strength_Report.pdf")
pdf2 <- unlist(str_split(pdf_txt, "[\\r\\n]+"))
pdf3 <- str_split_fixed(str_trim(pdf2), "\\s{2,}", 5)
write.xlsx(pdf2,"test2.xlsx")